benchmarks:

  openml_cc18:
    description: "OpenML Curated Classification Benchmark (CC18)"
    type: openml_suite
    suite_name: "OpenML-CC18"
    expected_num_tasks: 72
    task_type: classification

  openml_cc18_100:
    description: "OpenML CC18 (datasets with <= 100k instances)"
    type: openml_suite
    suite_name: "OpenML-CC18"
    max_instances: 100000
    task_type: classification

  openml_100:
    description: "OpenML-100 Benchmark"
    type: openml_suite
    suite_name: "OpenML100"
    expected_num_tasks: 100
    task_type: classification

  openml_regression_ctr23:
    description: "OpenML Curated Tabular Regression (CTR23)"
    type: openml_suite
    suite_id: "353"
    task_type: regression

  # openml_clustering:
  # description: "OpenML curated clustering benchmark"
  # type: openml_suite
  # suite_id:  
  # task_type: clustering

  openml_automl_benchmark:
    description: "OpenML AutoML Benchmark"
    type: openml_suite
    suite_id: "218"  
    task_type: classification

  # openml_time_series:
  #   description: "OpenML curated time series classification benchmark"
  #   type: openml_suite
  #   suite_name: "OpenML-TimeSeries"
  #   task_type: time_series_classification